spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        #git信息维护
        git:
          uri: https://github.com/liyiliuuu/SpringCloudConfig/
          search-paths: respo
      label: master
server:
  port: 8888
#配置服务注册中心
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  security:
    enabled: false